apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: sample-category 
  version: 0.1.0
  annotations:
    categories: sample-category
spec:
  displayName: sample-category chaos
  categoryDescription: >
    it exec inside target pods to run the chaos inject commands, waits for the chaos duration and revert the chaos 
  experiments:
  - sample-exec-chaos
  keywords: 
    - "pods" 
    - "kubernetes" 
    - "sample-category" 
    - "exec"
  maintainers: 
    - name: ksatchit 
      email: ksatchit@chaosnative.com
  minKubeVersion: 1.12.0 
  provider: 
    name: ChaosNative
  links: 
    - name: Documentation 
      url: https://docs.litmuschaos.io/docs/getstarted/ 
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/sample-category/experiments.yaml