apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    it execs inside target pods to run the chaos inject commands, waits for the chaos duration and reverts the chaos
kind: ChaosExperiment
metadata:
  name: pod-cpu-stress
  labels:
    name: pod-cpu-stress
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: latest
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups:
          - ""
          - "batch"
          - "apps"
          - "litmuschaos.io"
        resources:
          - "jobs"
          - "pods"
          - "pods/log"
          - "events"
          - "deployments"
          - "replicasets"
          - "pods/exec"
          - "chaosengines"
          - "chaosexperiments"
          - "chaosresults"
        verbs:
          - "create"
          - "list"
          - "get"
          - "patch"
          - "update"
          - "delete"
          - "deletecollection"
    image: "shubh214/go-runner:byoc-fault"
    imagePullPolicy: Always
    args:
      - -c
      - ./experiments -name pod-cpu-hog-exec
    command:
      - /bin/bash
    env:

      - name: TOTAL_CHAOS_DURATION
        value: '60'

      - name: RAMP_TIME
        value: ''

      - name: CHAOS_INJECT_COMMAND
        value: 'md5sum /dev/zero'

      # The command to kill the chaos process
      - name: CHAOS_KILL_COMMAND
        value: "kill $(find /proc -name exe -lname '*/md5sum' 2>&1 | grep -v 'Permission denied' | awk -F/ '{print $(NF-1)}')"

    labels:
      name: pod-cpu-stress
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: latest
