apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: sample-exec-chaos 
  version: 0.1.0
  annotations:
    categories: sample-category
spec:
  displayName: sample-exec-chaos 
  categoryDescription: >
    it exec inside target pods to run the chaos inject commands, waits for the chaos duration and revert the chaos 
  keywords: 
    - "pods" 
    - "kubernetes" 
    - "sample-category" 
    - "exec"
  platforms: 
    - "Minikube"
  maturity: alpha
  maintainers: 
    - name: ksatchit 
      email: ksatchit@chaosnative.com 
  minKubeVersion: 1.12.0 
  provider: 
    name: ChaosNative
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: latest
  links: 
    - name: Documentation 
      url: https://docs.litmuschaos.io/docs/getstarted/ 
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/sample-category/sample-exec-chaos/experiment.yaml